language: scala

scala:
  - 2.10.4
  - 2.11.8

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

matrix:
  fast_finish: true
#  allow_failures:
#    - jdk: oraclejdk8

cache:
  directories:
  - $HOME/.ivy2

before_install:
  - sudo add-apt-repository -y ppa:wnoronha/thrift
  - sudo apt-get update -qq
  - sudo apt-get install -qq thrift-compiler
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts

after_success: "project/submit_coveralls_once.sh"
